# Generated by Django 5.0.4 on 2024-05-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigSmiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='username',
            new_name='name',
        ),
    ]
