# Generated by Django 5.0.4 on 2024-05-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BigSmiles', '0003_user_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='national_id_number',
        ),
    ]
